// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/lavralex/fairy_tale_bot/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// CreateCartItem provides a mock function with given fields: ctx, item
func (_m *MockStorage) CreateCartItem(ctx context.Context, item models.CartItem) (models.CartItem, error) {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for CreateCartItem")
	}

	var r0 models.CartItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CartItem) (models.CartItem, error)); ok {
		return rf(ctx, item)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CartItem) models.CartItem); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Get(0).(models.CartItem)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CartItem) error); ok {
		r1 = rf(ctx, item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_CreateCartItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCartItem'
type MockStorage_CreateCartItem_Call struct {
	*mock.Call
}

// CreateCartItem is a helper method to define mock.On call
//   - ctx context.Context
//   - item models.CartItem
func (_e *MockStorage_Expecter) CreateCartItem(ctx interface{}, item interface{}) *MockStorage_CreateCartItem_Call {
	return &MockStorage_CreateCartItem_Call{Call: _e.mock.On("CreateCartItem", ctx, item)}
}

func (_c *MockStorage_CreateCartItem_Call) Run(run func(ctx context.Context, item models.CartItem)) *MockStorage_CreateCartItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.CartItem))
	})
	return _c
}

func (_c *MockStorage_CreateCartItem_Call) Return(_a0 models.CartItem, _a1 error) *MockStorage_CreateCartItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_CreateCartItem_Call) RunAndReturn(run func(context.Context, models.CartItem) (models.CartItem, error)) *MockStorage_CreateCartItem_Call {
	_c.Call.Return(run)
	return _c
}

// CreateField provides a mock function with given fields: ctx, field
func (_m *MockStorage) CreateField(ctx context.Context, field models.Field) (models.Field, error) {
	ret := _m.Called(ctx, field)

	if len(ret) == 0 {
		panic("no return value specified for CreateField")
	}

	var r0 models.Field
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Field) (models.Field, error)); ok {
		return rf(ctx, field)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Field) models.Field); ok {
		r0 = rf(ctx, field)
	} else {
		r0 = ret.Get(0).(models.Field)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Field) error); ok {
		r1 = rf(ctx, field)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_CreateField_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateField'
type MockStorage_CreateField_Call struct {
	*mock.Call
}

// CreateField is a helper method to define mock.On call
//   - ctx context.Context
//   - field models.Field
func (_e *MockStorage_Expecter) CreateField(ctx interface{}, field interface{}) *MockStorage_CreateField_Call {
	return &MockStorage_CreateField_Call{Call: _e.mock.On("CreateField", ctx, field)}
}

func (_c *MockStorage_CreateField_Call) Run(run func(ctx context.Context, field models.Field)) *MockStorage_CreateField_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Field))
	})
	return _c
}

func (_c *MockStorage_CreateField_Call) Return(_a0 models.Field, _a1 error) *MockStorage_CreateField_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_CreateField_Call) RunAndReturn(run func(context.Context, models.Field) (models.Field, error)) *MockStorage_CreateField_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOption provides a mock function with given fields: ctx, option
func (_m *MockStorage) CreateOption(ctx context.Context, option models.FieldOption) (models.FieldOption, error) {
	ret := _m.Called(ctx, option)

	if len(ret) == 0 {
		panic("no return value specified for CreateOption")
	}

	var r0 models.FieldOption
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.FieldOption) (models.FieldOption, error)); ok {
		return rf(ctx, option)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.FieldOption) models.FieldOption); ok {
		r0 = rf(ctx, option)
	} else {
		r0 = ret.Get(0).(models.FieldOption)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.FieldOption) error); ok {
		r1 = rf(ctx, option)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_CreateOption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOption'
type MockStorage_CreateOption_Call struct {
	*mock.Call
}

// CreateOption is a helper method to define mock.On call
//   - ctx context.Context
//   - option models.FieldOption
func (_e *MockStorage_Expecter) CreateOption(ctx interface{}, option interface{}) *MockStorage_CreateOption_Call {
	return &MockStorage_CreateOption_Call{Call: _e.mock.On("CreateOption", ctx, option)}
}

func (_c *MockStorage_CreateOption_Call) Run(run func(ctx context.Context, option models.FieldOption)) *MockStorage_CreateOption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.FieldOption))
	})
	return _c
}

func (_c *MockStorage_CreateOption_Call) Return(_a0 models.FieldOption, _a1 error) *MockStorage_CreateOption_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_CreateOption_Call) RunAndReturn(run func(context.Context, models.FieldOption) (models.FieldOption, error)) *MockStorage_CreateOption_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProduct provides a mock function with given fields: ctx, product
func (_m *MockStorage) CreateProduct(ctx context.Context, product models.Product) (models.Product, error) {
	ret := _m.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Product) (models.Product, error)); ok {
		return rf(ctx, product)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Product) models.Product); ok {
		r0 = rf(ctx, product)
	} else {
		r0 = ret.Get(0).(models.Product)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Product) error); ok {
		r1 = rf(ctx, product)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_CreateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProduct'
type MockStorage_CreateProduct_Call struct {
	*mock.Call
}

// CreateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - product models.Product
func (_e *MockStorage_Expecter) CreateProduct(ctx interface{}, product interface{}) *MockStorage_CreateProduct_Call {
	return &MockStorage_CreateProduct_Call{Call: _e.mock.On("CreateProduct", ctx, product)}
}

func (_c *MockStorage_CreateProduct_Call) Run(run func(ctx context.Context, product models.Product)) *MockStorage_CreateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Product))
	})
	return _c
}

func (_c *MockStorage_CreateProduct_Call) Return(_a0 models.Product, _a1 error) *MockStorage_CreateProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_CreateProduct_Call) RunAndReturn(run func(context.Context, models.Product) (models.Product, error)) *MockStorage_CreateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTemplate provides a mock function with given fields: ctx, template
func (_m *MockStorage) CreateTemplate(ctx context.Context, template models.Template) (models.Template, error) {
	ret := _m.Called(ctx, template)

	if len(ret) == 0 {
		panic("no return value specified for CreateTemplate")
	}

	var r0 models.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Template) (models.Template, error)); ok {
		return rf(ctx, template)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Template) models.Template); ok {
		r0 = rf(ctx, template)
	} else {
		r0 = ret.Get(0).(models.Template)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Template) error); ok {
		r1 = rf(ctx, template)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_CreateTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTemplate'
type MockStorage_CreateTemplate_Call struct {
	*mock.Call
}

// CreateTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - template models.Template
func (_e *MockStorage_Expecter) CreateTemplate(ctx interface{}, template interface{}) *MockStorage_CreateTemplate_Call {
	return &MockStorage_CreateTemplate_Call{Call: _e.mock.On("CreateTemplate", ctx, template)}
}

func (_c *MockStorage_CreateTemplate_Call) Run(run func(ctx context.Context, template models.Template)) *MockStorage_CreateTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Template))
	})
	return _c
}

func (_c *MockStorage_CreateTemplate_Call) Return(_a0 models.Template, _a1 error) *MockStorage_CreateTemplate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_CreateTemplate_Call) RunAndReturn(run func(context.Context, models.Template) (models.Template, error)) *MockStorage_CreateTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCartItem provides a mock function with given fields: ctx, id
func (_m *MockStorage) DeleteCartItem(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCartItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_DeleteCartItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCartItem'
type MockStorage_DeleteCartItem_Call struct {
	*mock.Call
}

// DeleteCartItem is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockStorage_Expecter) DeleteCartItem(ctx interface{}, id interface{}) *MockStorage_DeleteCartItem_Call {
	return &MockStorage_DeleteCartItem_Call{Call: _e.mock.On("DeleteCartItem", ctx, id)}
}

func (_c *MockStorage_DeleteCartItem_Call) Run(run func(ctx context.Context, id int64)) *MockStorage_DeleteCartItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockStorage_DeleteCartItem_Call) Return(_a0 error) *MockStorage_DeleteCartItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_DeleteCartItem_Call) RunAndReturn(run func(context.Context, int64) error) *MockStorage_DeleteCartItem_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteField provides a mock function with given fields: ctx, id
func (_m *MockStorage) DeleteField(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteField")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_DeleteField_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteField'
type MockStorage_DeleteField_Call struct {
	*mock.Call
}

// DeleteField is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockStorage_Expecter) DeleteField(ctx interface{}, id interface{}) *MockStorage_DeleteField_Call {
	return &MockStorage_DeleteField_Call{Call: _e.mock.On("DeleteField", ctx, id)}
}

func (_c *MockStorage_DeleteField_Call) Run(run func(ctx context.Context, id int64)) *MockStorage_DeleteField_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockStorage_DeleteField_Call) Return(_a0 error) *MockStorage_DeleteField_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_DeleteField_Call) RunAndReturn(run func(context.Context, int64) error) *MockStorage_DeleteField_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOption provides a mock function with given fields: ctx, id
func (_m *MockStorage) DeleteOption(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOption")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_DeleteOption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOption'
type MockStorage_DeleteOption_Call struct {
	*mock.Call
}

// DeleteOption is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockStorage_Expecter) DeleteOption(ctx interface{}, id interface{}) *MockStorage_DeleteOption_Call {
	return &MockStorage_DeleteOption_Call{Call: _e.mock.On("DeleteOption", ctx, id)}
}

func (_c *MockStorage_DeleteOption_Call) Run(run func(ctx context.Context, id int64)) *MockStorage_DeleteOption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockStorage_DeleteOption_Call) Return(_a0 error) *MockStorage_DeleteOption_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_DeleteOption_Call) RunAndReturn(run func(context.Context, int64) error) *MockStorage_DeleteOption_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProduct provides a mock function with given fields: ctx, id
func (_m *MockStorage) DeleteProduct(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_DeleteProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProduct'
type MockStorage_DeleteProduct_Call struct {
	*mock.Call
}

// DeleteProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockStorage_Expecter) DeleteProduct(ctx interface{}, id interface{}) *MockStorage_DeleteProduct_Call {
	return &MockStorage_DeleteProduct_Call{Call: _e.mock.On("DeleteProduct", ctx, id)}
}

func (_c *MockStorage_DeleteProduct_Call) Run(run func(ctx context.Context, id int64)) *MockStorage_DeleteProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockStorage_DeleteProduct_Call) Return(_a0 error) *MockStorage_DeleteProduct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_DeleteProduct_Call) RunAndReturn(run func(context.Context, int64) error) *MockStorage_DeleteProduct_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTemplate provides a mock function with given fields: ctx, id
func (_m *MockStorage) DeleteTemplate(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTemplate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_DeleteTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTemplate'
type MockStorage_DeleteTemplate_Call struct {
	*mock.Call
}

// DeleteTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockStorage_Expecter) DeleteTemplate(ctx interface{}, id interface{}) *MockStorage_DeleteTemplate_Call {
	return &MockStorage_DeleteTemplate_Call{Call: _e.mock.On("DeleteTemplate", ctx, id)}
}

func (_c *MockStorage_DeleteTemplate_Call) Run(run func(ctx context.Context, id int64)) *MockStorage_DeleteTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockStorage_DeleteTemplate_Call) Return(_a0 error) *MockStorage_DeleteTemplate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_DeleteTemplate_Call) RunAndReturn(run func(context.Context, int64) error) *MockStorage_DeleteTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// GetCart provides a mock function with given fields: ctx, userID
func (_m *MockStorage) GetCart(ctx context.Context, userID int64) ([]models.CartItem, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCart")
	}

	var r0 []models.CartItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]models.CartItem, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []models.CartItem); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.CartItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCart'
type MockStorage_GetCart_Call struct {
	*mock.Call
}

// GetCart is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockStorage_Expecter) GetCart(ctx interface{}, userID interface{}) *MockStorage_GetCart_Call {
	return &MockStorage_GetCart_Call{Call: _e.mock.On("GetCart", ctx, userID)}
}

func (_c *MockStorage_GetCart_Call) Run(run func(ctx context.Context, userID int64)) *MockStorage_GetCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockStorage_GetCart_Call) Return(_a0 []models.CartItem, _a1 error) *MockStorage_GetCart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetCart_Call) RunAndReturn(run func(context.Context, int64) ([]models.CartItem, error)) *MockStorage_GetCart_Call {
	_c.Call.Return(run)
	return _c
}

// GetField provides a mock function with given fields: ctx, id
func (_m *MockStorage) GetField(ctx context.Context, id int64) (models.Field, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetField")
	}

	var r0 models.Field
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (models.Field, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) models.Field); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Field)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetField_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetField'
type MockStorage_GetField_Call struct {
	*mock.Call
}

// GetField is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockStorage_Expecter) GetField(ctx interface{}, id interface{}) *MockStorage_GetField_Call {
	return &MockStorage_GetField_Call{Call: _e.mock.On("GetField", ctx, id)}
}

func (_c *MockStorage_GetField_Call) Run(run func(ctx context.Context, id int64)) *MockStorage_GetField_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockStorage_GetField_Call) Return(_a0 models.Field, _a1 error) *MockStorage_GetField_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetField_Call) RunAndReturn(run func(context.Context, int64) (models.Field, error)) *MockStorage_GetField_Call {
	_c.Call.Return(run)
	return _c
}

// GetFields provides a mock function with given fields: ctx
func (_m *MockStorage) GetFields(ctx context.Context) ([]models.Field, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetFields")
	}

	var r0 []models.Field
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Field, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Field); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Field)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFields'
type MockStorage_GetFields_Call struct {
	*mock.Call
}

// GetFields is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorage_Expecter) GetFields(ctx interface{}) *MockStorage_GetFields_Call {
	return &MockStorage_GetFields_Call{Call: _e.mock.On("GetFields", ctx)}
}

func (_c *MockStorage_GetFields_Call) Run(run func(ctx context.Context)) *MockStorage_GetFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStorage_GetFields_Call) Return(_a0 []models.Field, _a1 error) *MockStorage_GetFields_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetFields_Call) RunAndReturn(run func(context.Context) ([]models.Field, error)) *MockStorage_GetFields_Call {
	_c.Call.Return(run)
	return _c
}

// GetProduct provides a mock function with given fields: ctx, id
func (_m *MockStorage) GetProduct(ctx context.Context, id int64) (models.Product, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProduct")
	}

	var r0 models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (models.Product, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) models.Product); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Product)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProduct'
type MockStorage_GetProduct_Call struct {
	*mock.Call
}

// GetProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockStorage_Expecter) GetProduct(ctx interface{}, id interface{}) *MockStorage_GetProduct_Call {
	return &MockStorage_GetProduct_Call{Call: _e.mock.On("GetProduct", ctx, id)}
}

func (_c *MockStorage_GetProduct_Call) Run(run func(ctx context.Context, id int64)) *MockStorage_GetProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockStorage_GetProduct_Call) Return(_a0 models.Product, _a1 error) *MockStorage_GetProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetProduct_Call) RunAndReturn(run func(context.Context, int64) (models.Product, error)) *MockStorage_GetProduct_Call {
	_c.Call.Return(run)
	return _c
}

// GetProducts provides a mock function with given fields: ctx, limit, offset
func (_m *MockStorage) GetProducts(ctx context.Context, limit int, offset int) ([]models.Product, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetProducts")
	}

	var r0 []models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]models.Product, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []models.Product); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProducts'
type MockStorage_GetProducts_Call struct {
	*mock.Call
}

// GetProducts is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockStorage_Expecter) GetProducts(ctx interface{}, limit interface{}, offset interface{}) *MockStorage_GetProducts_Call {
	return &MockStorage_GetProducts_Call{Call: _e.mock.On("GetProducts", ctx, limit, offset)}
}

func (_c *MockStorage_GetProducts_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockStorage_GetProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockStorage_GetProducts_Call) Return(_a0 []models.Product, _a1 error) *MockStorage_GetProducts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetProducts_Call) RunAndReturn(run func(context.Context, int, int) ([]models.Product, error)) *MockStorage_GetProducts_Call {
	_c.Call.Return(run)
	return _c
}

// GetTemplate provides a mock function with given fields: ctx, id
func (_m *MockStorage) GetTemplate(ctx context.Context, id int64) (models.Template, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplate")
	}

	var r0 models.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (models.Template, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) models.Template); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Template)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemplate'
type MockStorage_GetTemplate_Call struct {
	*mock.Call
}

// GetTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockStorage_Expecter) GetTemplate(ctx interface{}, id interface{}) *MockStorage_GetTemplate_Call {
	return &MockStorage_GetTemplate_Call{Call: _e.mock.On("GetTemplate", ctx, id)}
}

func (_c *MockStorage_GetTemplate_Call) Run(run func(ctx context.Context, id int64)) *MockStorage_GetTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockStorage_GetTemplate_Call) Return(_a0 models.Template, _a1 error) *MockStorage_GetTemplate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetTemplate_Call) RunAndReturn(run func(context.Context, int64) (models.Template, error)) *MockStorage_GetTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// GetTemplates provides a mock function with given fields: ctx, limit, offset
func (_m *MockStorage) GetTemplates(ctx context.Context, limit int, offset int) ([]models.Template, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplates")
	}

	var r0 []models.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]models.Template, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []models.Template); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Template)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetTemplates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemplates'
type MockStorage_GetTemplates_Call struct {
	*mock.Call
}

// GetTemplates is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockStorage_Expecter) GetTemplates(ctx interface{}, limit interface{}, offset interface{}) *MockStorage_GetTemplates_Call {
	return &MockStorage_GetTemplates_Call{Call: _e.mock.On("GetTemplates", ctx, limit, offset)}
}

func (_c *MockStorage_GetTemplates_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockStorage_GetTemplates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockStorage_GetTemplates_Call) Return(_a0 []models.Template, _a1 error) *MockStorage_GetTemplates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetTemplates_Call) RunAndReturn(run func(context.Context, int, int) ([]models.Template, error)) *MockStorage_GetTemplates_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByTelegramID provides a mock function with given fields: ctx, userTelegramID
func (_m *MockStorage) GetUserByTelegramID(ctx context.Context, userTelegramID int64) (*models.User, error) {
	ret := _m.Called(ctx, userTelegramID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByTelegramID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.User, error)); ok {
		return rf(ctx, userTelegramID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.User); ok {
		r0 = rf(ctx, userTelegramID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userTelegramID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetUserByTelegramID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByTelegramID'
type MockStorage_GetUserByTelegramID_Call struct {
	*mock.Call
}

// GetUserByTelegramID is a helper method to define mock.On call
//   - ctx context.Context
//   - userTelegramID int64
func (_e *MockStorage_Expecter) GetUserByTelegramID(ctx interface{}, userTelegramID interface{}) *MockStorage_GetUserByTelegramID_Call {
	return &MockStorage_GetUserByTelegramID_Call{Call: _e.mock.On("GetUserByTelegramID", ctx, userTelegramID)}
}

func (_c *MockStorage_GetUserByTelegramID_Call) Run(run func(ctx context.Context, userTelegramID int64)) *MockStorage_GetUserByTelegramID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockStorage_GetUserByTelegramID_Call) Return(_a0 *models.User, _a1 error) *MockStorage_GetUserByTelegramID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetUserByTelegramID_Call) RunAndReturn(run func(context.Context, int64) (*models.User, error)) *MockStorage_GetUserByTelegramID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateField provides a mock function with given fields: ctx, field
func (_m *MockStorage) UpdateField(ctx context.Context, field models.Field) (models.Field, error) {
	ret := _m.Called(ctx, field)

	if len(ret) == 0 {
		panic("no return value specified for UpdateField")
	}

	var r0 models.Field
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Field) (models.Field, error)); ok {
		return rf(ctx, field)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Field) models.Field); ok {
		r0 = rf(ctx, field)
	} else {
		r0 = ret.Get(0).(models.Field)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Field) error); ok {
		r1 = rf(ctx, field)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_UpdateField_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateField'
type MockStorage_UpdateField_Call struct {
	*mock.Call
}

// UpdateField is a helper method to define mock.On call
//   - ctx context.Context
//   - field models.Field
func (_e *MockStorage_Expecter) UpdateField(ctx interface{}, field interface{}) *MockStorage_UpdateField_Call {
	return &MockStorage_UpdateField_Call{Call: _e.mock.On("UpdateField", ctx, field)}
}

func (_c *MockStorage_UpdateField_Call) Run(run func(ctx context.Context, field models.Field)) *MockStorage_UpdateField_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Field))
	})
	return _c
}

func (_c *MockStorage_UpdateField_Call) Return(_a0 models.Field, _a1 error) *MockStorage_UpdateField_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_UpdateField_Call) RunAndReturn(run func(context.Context, models.Field) (models.Field, error)) *MockStorage_UpdateField_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOption provides a mock function with given fields: ctx, option
func (_m *MockStorage) UpdateOption(ctx context.Context, option models.FieldOption) (models.FieldOption, error) {
	ret := _m.Called(ctx, option)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOption")
	}

	var r0 models.FieldOption
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.FieldOption) (models.FieldOption, error)); ok {
		return rf(ctx, option)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.FieldOption) models.FieldOption); ok {
		r0 = rf(ctx, option)
	} else {
		r0 = ret.Get(0).(models.FieldOption)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.FieldOption) error); ok {
		r1 = rf(ctx, option)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_UpdateOption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOption'
type MockStorage_UpdateOption_Call struct {
	*mock.Call
}

// UpdateOption is a helper method to define mock.On call
//   - ctx context.Context
//   - option models.FieldOption
func (_e *MockStorage_Expecter) UpdateOption(ctx interface{}, option interface{}) *MockStorage_UpdateOption_Call {
	return &MockStorage_UpdateOption_Call{Call: _e.mock.On("UpdateOption", ctx, option)}
}

func (_c *MockStorage_UpdateOption_Call) Run(run func(ctx context.Context, option models.FieldOption)) *MockStorage_UpdateOption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.FieldOption))
	})
	return _c
}

func (_c *MockStorage_UpdateOption_Call) Return(_a0 models.FieldOption, _a1 error) *MockStorage_UpdateOption_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_UpdateOption_Call) RunAndReturn(run func(context.Context, models.FieldOption) (models.FieldOption, error)) *MockStorage_UpdateOption_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProduct provides a mock function with given fields: ctx, product
func (_m *MockStorage) UpdateProduct(ctx context.Context, product models.Product) (models.Product, error) {
	ret := _m.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Product) (models.Product, error)); ok {
		return rf(ctx, product)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Product) models.Product); ok {
		r0 = rf(ctx, product)
	} else {
		r0 = ret.Get(0).(models.Product)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Product) error); ok {
		r1 = rf(ctx, product)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_UpdateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProduct'
type MockStorage_UpdateProduct_Call struct {
	*mock.Call
}

// UpdateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - product models.Product
func (_e *MockStorage_Expecter) UpdateProduct(ctx interface{}, product interface{}) *MockStorage_UpdateProduct_Call {
	return &MockStorage_UpdateProduct_Call{Call: _e.mock.On("UpdateProduct", ctx, product)}
}

func (_c *MockStorage_UpdateProduct_Call) Run(run func(ctx context.Context, product models.Product)) *MockStorage_UpdateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Product))
	})
	return _c
}

func (_c *MockStorage_UpdateProduct_Call) Return(_a0 models.Product, _a1 error) *MockStorage_UpdateProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_UpdateProduct_Call) RunAndReturn(run func(context.Context, models.Product) (models.Product, error)) *MockStorage_UpdateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTemplate provides a mock function with given fields: ctx, template
func (_m *MockStorage) UpdateTemplate(ctx context.Context, template models.Template) (models.Template, error) {
	ret := _m.Called(ctx, template)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTemplate")
	}

	var r0 models.Template
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Template) (models.Template, error)); ok {
		return rf(ctx, template)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Template) models.Template); ok {
		r0 = rf(ctx, template)
	} else {
		r0 = ret.Get(0).(models.Template)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Template) error); ok {
		r1 = rf(ctx, template)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_UpdateTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTemplate'
type MockStorage_UpdateTemplate_Call struct {
	*mock.Call
}

// UpdateTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - template models.Template
func (_e *MockStorage_Expecter) UpdateTemplate(ctx interface{}, template interface{}) *MockStorage_UpdateTemplate_Call {
	return &MockStorage_UpdateTemplate_Call{Call: _e.mock.On("UpdateTemplate", ctx, template)}
}

func (_c *MockStorage_UpdateTemplate_Call) Run(run func(ctx context.Context, template models.Template)) *MockStorage_UpdateTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Template))
	})
	return _c
}

func (_c *MockStorage_UpdateTemplate_Call) Return(_a0 models.Template, _a1 error) *MockStorage_UpdateTemplate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_UpdateTemplate_Call) RunAndReturn(run func(context.Context, models.Template) (models.Template, error)) *MockStorage_UpdateTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
